<a href="https://colab.research.google.com/github/Ruchi0000/RL/blob/main/Experiment_7(Policy_Iteration).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import math

grid = np.zeros((3, 4))
grid[1, 1] = math.inf
grid[0, 3], grid[1, 3] = 1, -1

operation_grid = np.array([["R", "R", "R", 1],
                           ["U", 0, "U", -1],
                           ["U", "R", "U", "L"]])

g = 0.9
max_iterations = 100
tolerance = 1e-6

print(operation_grid)
print()
print(grid)

old_grid = grid.copy()
new_grid = np.zeros((3, 4))
grid_data = np.zeros((max_iterations, 3, 4))
max_change_list = []

for y in range(max_iterations):
    max_change = 0
    for i in range(0, 3):
        for j in range(0, 4):
            if operation_grid[i][j] == "R" and j < 3:
                new_value = old_grid[i][j + 1]
            elif operation_grid[i][j] == "U" and i > 0:
                new_value = old_grid[i - 1][j]
            elif operation_grid[i][j] == "L" and j > 0:
                new_value = old_grid[i][j - 1]
            else:
                continue

            new_grid[i][j] = g * new_value
            change = abs(new_grid[i][j] - old_grid[i][j])
            max_change = max(max_change, change)

    max_change_list.append(max_change)
    print(f"Iteration {y + 1}, Max Change: {max_change}")
    print()
    print(new_grid)

    grid_data[y] = new_grid
    old_grid = new_grid.copy()

    if max_change < tolerance:
        break


[['R' 'R' 'R' '1']
 ['U' '0' 'U' '-1']
 ['U' 'R' 'U' 'L']]

[[ 0.  0.  0.  1.]
 [ 0. inf  0. -1.]
 [ 0.  0.  0.  0.]]
Iteration 1, Max Change: 0.9

[[0.  0.  0.9 0. ]
 [0.  0.  0.  0. ]
 [0.  0.  0.  0. ]]
Iteration 2, Max Change: 0.9

[[0.   0.81 0.   0.  ]
 [0.   0.   0.81 0.  ]
 [0.   0.   0.   0.  ]]
Iteration 3, Max Change: 0.81

[[0.729 0.    0.    0.   ]
 [0.    0.    0.    0.   ]
 [0.    0.    0.729 0.   ]]
Iteration 4, Max Change: 0.7290000000000001

[[0.     0.     0.     0.    ]
 [0.6561 0.     0.     0.    ]
 [0.     0.6561 0.     0.6561]]
Iteration 5, Max Change: 0.6561000000000001

[[0.      0.      0.      0.     ]
 [0.      0.      0.      0.     ]
 [0.59049 0.      0.      0.     ]]
Iteration 6, Max Change: 0.5904900000000002

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Iteration 7, Max Change: 0

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
